# Generated by Django 5.0 on 2024-04-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
